#### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [11]:
N = int(input('Введите число: '))
np.arange(0,N)[::-1]

Введите число: 15


array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [29]:
N = int(input('Введите число: '))
a = np.diag(np.arange(0,N,1)[::-1])

Введите число: 5


In [30]:
a

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [31]:
sum = 0
for i,el in enumerate(a):
    sum+=el[i]
print(sum)

10


##### Если правильно понял смысл задания

Задание 3
Решите систему уравнений:
    4x + 2y + z = 4
    x + 3y = 12
    5y + 4z = -3

In [46]:
a = np.array([[4,2,1],
              [1,3,0],
              [0,5,4]])
b = np.array([4,12,-3])

In [49]:
from numpy import linalg

In [50]:
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [51]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

#### Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [53]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [54]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [57]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [64]:
max_cos = 0
number_user = 0
for i, user in enumerate(users_stats):
    if cosine(user,next_user_stats) >= max_cos:
        max_cos = cosine(user,next_user_stats)
        number_user = i
print(f'Пользователь номер {number_user + 1} имеет максимальное косинусное сходство: {max_cos}')

Пользователь номер 8 имеет максимальное косинусное сходство: 0.9486832980505138
